"""Demo: ingest chunk JSON (from the parse service) into the chunks table.

The right half of the chunk seam (SIM-338) -- reads the JSON scripts/emit_chunks.py
produced in the parse repo, embeds each chunk via the Alpha embedder (voyage-4-large,
SIM-245), and INSERTs into the `chunks` table through the app's real model + session,
as the app role, under a tenant context. The chunk-side sibling of ingest_claims.

SAFETY, by construction (same as ingest_claims):
- Dry run by DEFAULT. Everything happens inside one transaction that is ROLLED
  BACK unless --commit is passed. A plain run leaves the database untouched.
- Inserts run as dd_app (SET LOCAL ROLE), not the owner, so RLS is exercised.
- --org-key names a demo tenant; its organisation row is created in the same
  transaction, so it too vanishes on rollback.
- Embeddings cost a Voyage call and a key, so only --commit (the persisting run)
  embeds; a dry run exercises the write path with a NULL embedding.

    uv run python scripts/ingest_chunks.py chunks.json --org-key demo
    VOYAGE_API_KEY=... uv run python scripts/ingest_chunks.py chunks.json --org-key demo --commit

Two translations are the ingest's job (the chunks table has no column for either
as-is): scale_context folds into the stored/embedded `content` so the scale is
both embedded and searchable, and the parser's source sha256 becomes the table's
UUID `document_id` (a stable stand-in until a data_sources table exists).
"""

from __future__ import annotations

import argparse
import asyncio
import json
import uuid
from pathlib import Path

from sqlalchemy import func, select, text

from app.core.database import AsyncSessionLocal
from app.models import Chunk, Organisation
from app.models.organisation import OrgType
from app.services.embedding import get_embedder


def _fold_content(chunk: dict) -> str:
    """The text that becomes the stored + embedded `content`. scale_context (the
    table's scale banner, e.g. "$ in millions") folds in as a prefix so the scale
    is both embedded (dense leg) and searchable (sparse leg) -- SIM-338 sub-task
    3. The chunks table has no scale_context column; this is the decision to
    carry it in `content` rather than add one."""
    content = chunk["content"]
    scale = chunk.get("scale_context")
    return f"[{scale}] {content}" if scale else content


def _span(chunk: dict) -> tuple[int | None, int | None]:
    """A single (char_start, char_end) for the chunks table from the chunk's
    per-block `spans`. Prose carries one span per source block; the covering
    range (min start, max end) is the chunk's page extent. Tables and charts
    carry no span (their citation is the bbox), so both come back NULL."""
    spans = chunk.get("spans") or []
    if not spans:
        return None, None
    return min(s[0] for s in spans), max(s[1] for s in spans)


def _document_uuid(document_id: str) -> uuid.UUID:
    """Map the parser's source sha256 to the chunks table's UUID `document_id`.
    A data_sources table (the real sha256 -> id map) does not exist yet, so this
    derives a STABLE uuid5 from the sha256: every chunk of one document shares it,
    so the document_id retrieval filter (SIM-336) works today, and it remaps
    cleanly to a real data_source id once that table lands."""
    return uuid.uuid5(uuid.NAMESPACE_OID, document_id)


def _row_from_chunk(
    chunk: dict, org_id: int, *, embedding: list[float] | None, embedding_version: str | None
) -> Chunk:
    """One seam-JSON chunk -> one Chunk ORM row. content_tsv is generated by
    Postgres from `content`, so it is never set here."""
    char_start, char_end = _span(chunk)
    return Chunk(
        org_id=org_id,
        document_id=_document_uuid(chunk["document_id"]),
        content=_fold_content(chunk),
        embedding=embedding,
        embedding_version=embedding_version if embedding is not None else None,
        element_type=chunk["element_type"],
        page=chunk["page"],
        char_start=char_start,
        char_end=char_end,
    )


class _Rollback(Exception):
    """Sentinel to abandon the transaction on a dry run without an error exit."""


async def _run(payload: dict, org_key: str, commit: bool) -> None:
    chunks = payload["chunks"]
    print(f"{len(chunks)} chunks read from the seam.")

    # Embed BEFORE the transaction, so a Voyage failure aborts without leaving an
    # open tx -- and only on --commit, since embedding costs a call and a key.
    embeddings: list[list[float] | None] = [None] * len(chunks)
    embedding_version: str | None = None
    if commit and chunks:
        embedder = get_embedder()
        embeddings = list(await embedder.embed_documents([_fold_content(c) for c in chunks]))
        embedding_version = embedder.version
        print(f"embedded {len(embeddings)} chunks via {embedding_version}.")

    async with AsyncSessionLocal() as session, session.begin():
        # Run as dd_app under the tenant, exactly as the app would (so RLS applies
        # to the organisation insert too). See ingest_claims for the SET LOCAL
        # ROLE / set_config rationale.
        await session.execute(text("SET LOCAL ROLE dd_app"))
        await session.execute(text("SELECT set_config('app.org_id', :k, true)"), {"k": org_key})

        org = await session.scalar(select(Organisation).where(Organisation.clerk_org_id == org_key))
        if org is None:
            org = Organisation(
                clerk_org_id=org_key, name=f"E2E demo ({org_key})", type=OrgType.PE_FIRM
            )
            session.add(org)
            await session.flush()  # assigns org.id
        org_id = org.id

        for c, emb in zip(chunks, embeddings, strict=True):
            row = _row_from_chunk(c, org_id, embedding=emb, embedding_version=embedding_version)
            # SIM-218 (migration 77be2ddc60a0) added the FK
            # chunks.document_id -> data_source(id). This direct-ingest demo has no
            # real data_source row, so leave document_id NULL: the FK only binds
            # when non-null, and the sandbox retrieve path scopes by org, not
            # document_id. Seeding a real data_source row is the proper follow-up.
            row.document_id = None
            session.add(row)
        await session.flush()

        seen = await session.scalar(select(func.count()).select_from(Chunk))
        print(f"dd_app, tenant {org_key!r}: sees {seen} chunks (inserted {len(chunks)}).")

        await session.execute(text("SELECT set_config('app.org_id', 'some_other_org', true)"))
        other = await session.scalar(select(func.count()).select_from(Chunk))
        print(f"dd_app, a DIFFERENT tenant: sees {other} chunks (RLS isolation).")

        if commit:
            print("--commit: persisting.")
        else:
            raise _Rollback()


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("chunks_json", type=Path)
    parser.add_argument("--org-key", required=True, help="clerk_org_id for the demo tenant.")
    parser.add_argument("--commit", action="store_true", help="Persist. Default is a dry run.")
    args = parser.parse_args(argv)

    payload = json.loads(args.chunks_json.read_text())
    try:
        asyncio.run(_run(payload, args.org_key, args.commit))
    except _Rollback:
        print("dry run: transaction rolled back, database unchanged. Pass --commit to persist.")


if __name__ == "__main__":
    main()
